### ISSUE TITLE
Type N: not enough inpu

### ISSUE THREAD

**Issue by andris155** [ImagicalMine/ImagicalMine#231397]
- [x] This issue isn't related to any plugins or plugin related crashes.
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.
- [x] This issue matches the contributing guidelines - the link is just above the title field.

## Issue description
30.03 11:27:33 [Server] INFO Warning: unpack(): Type N: not enough input, need 4, have 0 in phar:///ImagicalMine.phar/src/pocketmine/utils/Binary.php on line 335

**Comment by Guillaume351** [comment]
Same problem. After a few seconds/minutes, makes the server impossible to join

**Comment by Guillaume351** [comment]
Still have the problem. Up ? It makes all the servers instable, even after a reboot, the error comes back. Sometimes it's gone, sometimes it come back..

**Comment by keithkfng** [comment]
Is it an IM issue?

**Comment by Guillaume351** [comment]
I don't have the problem with Nukkit (Java), and I didn't have it a few month ago. I think it is an IM issue

**Comment by Guillaume351** [comment]
I just tried with PocketMine : same problem, Type N error.
I did not have the issue before 0.14. I didn't change any of my plugins.
It's strange : I have 6 servers on my dedicated. During heavy periods (when a lot of players join) they ALL have the issue. On light periods (50 / 64 players on each servers), they do not have the issue. 

If I reboot, delete the worlds, delete all the players files, reboot the dedicated, it changes nothing.

**Comment by keithkfng** [comment]
PocketMine issue...

**Comment by remotevase** [comment]
I believe it is just an incompatibility with 0.14.1

**Comment by Guillaume351** [comment]
Moreover, when I start the server, before the Type N issue appear, I often see 1 or 2 connection which are timed out. Then, even if I try to connect, nothing appear. Finally, the Type N issue arrives.

I tried without any plugin, same issue. 
I repeat myself, but it's very strange : all servers works during 12 - 16 hours a day. Then, during more or less 8 hours a day (when there are the most people online worldwide), all servers get this issue.

I tried to disable player file saving, pocketmine stastics, and all things that could explain that this bug is simultaneous. 

(I host my servers on different dedicated servers.I rarely have the problem on MicroBattles (gamemode : Survival. 64 slots. 9 worlds loaded) but really often on Build Battle (gamemode : Creative. 64 slots. 9 worlds loaded).

Server log : disabled. Same settings on all servers (MicroBattles and Build Battle).

I also tried with the lastest ImagicalMine version : only thing that changes is that error is line 362.

Can you find an explanation why servers works 2/3 of the times, and in the 1/3 where there is the bug, even if I reboot server it doesn't work ? (I tried to reboot 20 - 30 times in a row)

**Comment by deotern** [comment]
//THIS IS NOT A IMAGICALMINE BUG
This is an UDP Flood Attack, the hardest attack to stop... You're in the hot soup...
Because my server is suffering from this attack and I get exactly the same error...

Solution: mitigate or stop the attack... (P/S: Reinstalling Pocketmine, restarting, etc won't fix it)

INFO: I notice that many people reporting this issue recently, there's a man behind all these attacks, I have no idea who is this

**Comment by remotevase** [comment]
Thanks, @deotern. Im sorry about your server, and thanks for the warning about some guy!

**Comment by Guillaume351** [comment]
And what server do you own @andris155 ? How many players connected ?

**Comment by andris155** [comment]
My server: **https://www.mikrovps.hu/vps/xen** (2 GB RAM, ubuntu)
40-50 players playing my server.

**Comment by Guillaume351** [comment]
@andris155 So you don't run a very large network ?

**Comment by remotevase** [comment]
what makes you say that? What do you mean by large? Large amount of players? He has a lot. Large amount of servers? well, thats complicated

**Comment by Guillaume351** [comment]
I mean large enough (players) to explain a DDoS / DoS attack

**Comment by remotevase** [comment]
oh
