### ISSUE TITLE
PluginManager.php Bug by ini our plugins

### ISSUE THREAD

**Issue by SurvivalHive** [ImagicalMine/ImagicalMine#231416]
```
if($compatible === false and $this->server->getProperty("settings.incompatible-plugins") === false){
                                $this->server->getLogger()->error($this->server->getLanguage()->translateString("pocketmine.plugin.loadError", [$name, "%pocketmine.plugin.incompatibleAPI"]));
                                continue;
                            }else{
                                $this->server->getLogger()->warning("Loading plugin '$name' with incompatible API version (the plugin API is not compatible with ImagicalMine API version " . $this->server->getApiVersion() . ")");
                            }
```
what is that?

**Comment by dterweij** [comment]
When set to true in your pocketmine.yml then you can load plugins =< 2.0.0 API.
Because only the API version number is bumped but no API changes are made the plugins just works. Altho the ones that are PHP7 compatible :)
If you set it to disable, then 99% of the plugins does not load at all because they have not the API 2.0.0 tag.
Just read the code and understand PHP. 
Next time ask this at the forum because this is a issue platform and not to ask things like this.
Close this.

**Comment by SurvivalHive** [comment]
you dont understand my problem dude... 

`else{
                                $this->server->getLogger()->warning("Loading plugin '$name' with incompatible API version (the plugin API is not compatible with ImagicalMine API version " . $this->server->getApiVersion() . ")");
                            }`

this let show an error by all plugins - but the plugins work without problems...

**Comment by TheDragonRing** [comment]
Yes, the error shows to alert you that the plugin has the wrong API version, even though it allows the plugin to work, issue closed.

**Comment by SurvivalHive** [comment]
fail... all plugins has right api version setted... but error still the same... but its ok dudes...

**Comment by TheDragonRing** [comment]
Yeah, well, what I said earlier is what I think is meant to happen, but not what actually happens xD I get same problem too
