### ISSUE TITLE
$this->getServer()->getLevels() only returns the loaded levels

### ISSUE THREAD

**Issue by thebigsmileXD** [ImagicalMine/ImagicalMine#595]
This is an annoying bug..
I was about to use my classic world adding method like i did on instantrespawn, oitc, spleef..
Now on hotpotato ```$this->getServer()->getLevels()``` only returns the loaded levels and i wondered 1 hour what the problem might be..

**Comment by legoboy0215** [comment]
??? This is expected behavior.

**Comment by MCDad** [comment]
@legoboy0215 - I'm not sure your comment is true.

SimplePortals v0.0.3 onEnable used to construct a map of all the portals on a server, regardless of whether they were loaded.  It called getLevelByName which in turn calls getLevels.  Everything worked fine until approximately the 3xx builds when SimplePortals started crashing the server.

Someone called JamJam raised an issue at https://github.com/Falkirks/SimplePortals/issues/5.  I've done some digging and added more detail.  It looks like SimplePortals fails because it can't build the portal store, because it can't get the level information.

SimplePortals has been static since November but obviously IM is in flux.

I think bigsmile is right, there's something up with getLevels.  My crash dump and server log posted again for reference.


[CrashDump_Tue_Jan_12-01.01.07-UTC_2016.log.pdf](https://github.com/ImagicalCorp/ImagicalMine/files/87281/CrashDump_Tue_Jan_12-01.01.07-UTC_2016.log.pdf)
[server.log.pdf](https://github.com/ImagicalCorp/ImagicalMine/files/87283/server.log.pdf)

**Comment by thebigsmileXD** [comment]
Thaaanks! Can you repost that in PocketMine? I've already opened an issue there before i did here.. Then i thought its im's fault and made one here

**Comment by ecoron** [comment]
i think getLevels() works fine, it just shows the levels actual loaded on the server, and this is the right behavior. i'm also didn't see the usecase to read all worlds from the worlds folder.
i think a clean solution is to add a method getAvailableLevels() which is returning all possible levels and there settings.
and an extension of the configuration in pocketmine.yml like this
```
worlds:
 world1:
  seed: 123
  generator: ...
  load: true
 world2:
  seed: 456
  generator: ...
  load: false
```
so maybe world2 is required by something, then it can loaded with loadLevel('world2')

**Comment by PocketKiller** [comment]
then why does
