### ISSUE TITLE
Latest php 7 0.14.0 not work pvp protection

### ISSUE THREAD

**Issue by andris155** [ImagicalMine/ImagicalMine#902]
Iprotector god mode = not work
LimitedCreative creative pvp protection = not work

**Comment by TheDragonRing** [comment]
Ummmmmmmm, why exactly are you asking for help here?
LimititedCreative and iProtector are plugins, if they aren't working properly then that is because there is some outdated or glitched code that doesn't work with php7 in them, or some other, similar (maybe), reason, but I'm pretty sure that this isn't because of bad code in ImagicalMine....
