### ISSUE TITLE
Server Crashing With Latest Builds 655,654,653,652 same crash report

### ISSUE THREAD

**Issue by FienixEC** [ImagicalMine/ImagicalMine#909]
This is my crash report ...... please help!

ImagicalMine Crash Dump Sat Feb 13 22:19:02 EST 2016

Error: Undefined offset: -1
File: /src/pocketmine/level/format/generic/BaseChunk
Line: 107
Type: notice

Code:
[98] 			return $this->sections[$y >> 4]->setBlock($x, $y & 0x0f, $z, $blockId & 0xff, $meta & 0x0f);
[99] 		}catch(ChunkException $e){
[100] 			$level = $this->getProvider();
[101] 			$this->setInternalSection($Y = $y >> 4, $level::createChunkSection($Y));
[102] 			return $this->sections[$y >> 4]->setBlock($x, $y & 0x0f, $z, $blockId & 0xff, $meta & 0x0f);
[103] 		}
[104] 	}
[105] 
[106] 	public function getBlockId($x, $y, $z){
[107] 		return $this->sections[$y >> 4]->getBlockId($x, $y & 0x0f, $z);
[108] 	}
[109] 
[110] 	public function setBlockId($x, $y, $z, $id){
[111] 		try{
[112] 			$this->sections[$y >> 4]->setBlockId($x, $y & 0x0f, $z, $id);
[113] 			$this->hasChanged = true;
[114] 		}catch(ChunkException $e){
[115] 			$level = $this->getProvider();
[116] 			$this->setInternalSection($Y = $y >> 4, $level::createChunkSection($Y));
[117] 			$this->setBlockId($x, $y, $z, $id);

Backtrace:
#0 /src/pocketmine/level/Level(2887): pocketmine\level\format\generic\BaseChunk->getBlockId(integer 12, integer -1, integer 13)
#1 /src/pocketmine/Player(769): pocketmine\level\Level->getSafeSpawn(pocketmine\Player Player(23))
#2 /src/pocketmine/Player(748): pocketmine\Player->doFirstSpawn(boolean)
#3 /src/pocketmine/Player(1678): pocketmine\Player->sendNextChunk(boolean)
#4 /src/pocketmine/Server(2594): pocketmine\Player->checkNetwork(boolean)
#5 /src/pocketmine/Server(2332): pocketmine\Server->tick(boolean)
#6 /src/pocketmine/Server(2210): pocketmine\Server->tickProcessor(boolean)
#7 /src/pocketmine/Server(1811): pocketmine\Server->start(boolean)
#8 /src/pocketmine/PocketMine(472): pocketmine\Server->__construct(pocketmine\CompatibleClassLoader object, pocketmine\utils\MainLogger object, string phar:///home/tcagame/elitecra/728/PocketMine-MP.phar/, string /home/tcagame/elitecra/728/, string /home/tcagame/elitecra/728/plugins/)
#9 (1): require_once(string phar:///home/tcagame/elitecra/728/PocketMine-MP.phar/src/pocketmine/PocketMine.php)

ImagicalMine version: 1.0dev #0 [Protocol 37; API 1.14.0]
Git commit:

**Comment by mwvent** [comment]
Looks like the old issue with corrupt player.dat files, does this happen just after a particular player / players join?
If this isnt a production server try renaming the players folder to players.old and see if you can join without the error. If you do find you can then join could you post the player.dat file of the player that caused the issue from the players folder here and I'll take a look at it.

From what I remember the bad player.dat files are not working because the y value is being saved with scientific notation that is not understood by IM when the file is loaded again, perhaps I can have a look at the loading functions and make sure it can deal with the scientific notation in the player co-ords and also try and prevent is saving with them

**Comment by PocketKiller** [comment]
@mwvent it happens when players go on Y 0, server crashes, then server restarts then that players joins again and server crashes because he spawn on Y 0.

**Comment by mwvent** [comment]
Yes I agree - on my lobby server I got this a lot because it was possible to fall into the void (EmptyWorld)

I did used to use this https://github.com/mwvent/pm_players_nbt_fix on my start.sh script, but then I modified it just rm the players folder each run as it isn't important for a lobby server. In the meantime I had just assumed the bug was fixed (this was ages ago) and I didn't keep any bad player.dat files to test with doh!

If you use an nbt tag viewer on the dat file you can see the 0.0000something co-ordinate gets saved in scientific notation (i.e. 0.00000000000000000000000000000012312321 = 1.2312321E-31. This gets interpreted as -1 when loading (which you can see in the Backtrace here)

You can just get safespawn/getblockid to check if the y value is <0 and set it to 1 but it doesn't fix the root problem I want to try and fix that if I can :-)

**Comment by mwvent** [comment]
Can anybody confirm this happens with the current source? I have injected a Y co-ord that used to cause the issue into the NBT on purpose - I have tested on master, php7, php7-0.14 branches and I just cant reproduce the bug anymore

In Level.php in all branches there is 

public function getSafeSpawn($spawn = null){
  if(!($spawn instanceof Vector3) or $spawn->y <= 0){
     $spawn = $this->getSpawnLocation();
  }

but then I see $wasAir = ($chunk->getBlockId($x, $y - 1, $z) === 0);

So that line could be calling getBlockId with y=-1 if getSafeSpawn is called with a y co-ord of less than 1

So I guess the 'fix' would be to either

 - change getSafeSpawn to ignore <= 1 instead of <= 0 but that would kick people who log back in after being over the bedrock back to spawn?
 - change getBlockId to ignore values of less than 0 - but it is called often and this may have a tiny efficiency impact
 - add a check after $v = $spawn->floor(); in getSafeSpawn to set $wasAir to false and not try and call getBlockId with a negative value

I would hate to just blindly commit without the 'bad' player dat file to test with first - but if nobody can get one I will commit the second option to the branches as long as nobody has any objections?
